server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/moddevyes/config-repo
          username: ${CONFIG_SERVER_USR}
          password: ${CONFIG_SERVER_PWD}
        native:
          search-locations: https://github.com/moddevyes/config-repo
logging:
  level:
    root: info
---
spring:
  application:
    name: commerce-config-server
  profiles:
    active: docker
  cloud:
    config-server:
      build: spring-cloud/config-server
      mem_limit: 512m
      environment:
        - SPRING_PROFILES_ACTIVE=docker,native
        - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
        - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
        - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
      server:
        git:
          uri: https://github.com/moddevyes/config-repo
          username: ${CONFIG_SERVER_USR}
          password: ${CONFIG_SERVER_PWD}
        native:
          search-locations: https://github.com/moddevyes/config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/